# Generated by Django 5.2.7 on 2025-11-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зураг')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'Ангилал',
                'verbose_name_plural': 'Ангиллууд',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Гарчиг')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features Section'), ('about', 'About Section'), ('testimonials', 'Testimonials'), ('cta', 'Call to Action'), ('custom', 'Custom Section')], default='custom', max_length=50, verbose_name='Хэсгийн төрөл')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Дэд гарчиг')),
                ('content', models.TextField(blank=True, verbose_name='Агуулга')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/', verbose_name='Зураг')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Товчны текст')),
                ('button_link', models.CharField(blank=True, max_length=500, verbose_name='Товчны холбоос')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
            ],
            options={
                'verbose_name': 'Landing хуудасны агуулга',
                'verbose_name_plural': 'Landing хуудасны агуулгууд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Нэр')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(verbose_name='Танилцуулга')),
                ('specifications', models.TextField(blank=True, help_text='Үзүүлэлтүүдийг мөр мөрөөр нь оруулна уу', verbose_name='Үзүүлэлтүүд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Үнэ')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Хямдралтай үнэ')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Нөөц')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Онцлох бүтээгдэхүүн')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүн',
                'verbose_name_plural': 'Бүтээгдэхүүнүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зураг')),
                ('is_main', models.BooleanField(default=False, verbose_name='Үндсэн зураг')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Бүтээгдэхүүн')),
            ],
            options={
                'verbose_name': 'Бүтээгдэхүүний зураг',
                'verbose_name_plural': 'Бүтээгдэхүүний зургууд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('sort_order', models.IntegerField(default=0, verbose_name='Эрэмбэ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/', verbose_name='Зураг')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Засварласан огноо')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Ангилал')),
            ],
            options={
                'verbose_name': 'Дэд ангилал',
                'verbose_name_plural': 'Дэд ангиллууд',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.subcategory', verbose_name='Дэд ангилал'),
        ),
    ]
